"""add back vars

Revision ID: 659807541929
Revises: f44bbd91e24d
Create Date: 2016-07-20 12:25:18.934083

"""

# revision identifiers, used by Alembic.
revision = '659807541929'
down_revision = 'f44bbd91e24d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home', sa.String(), nullable=True))
    op.add_column('game', sa.Column('oppo', sa.String(), nullable=True))
    op.add_column('game', sa.Column('oppo_runs', sa.String(), nullable=True))
    op.add_column('game', sa.Column('pens_runs', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'pens_runs')
    op.drop_column('game', 'oppo_runs')
    op.drop_column('game', 'oppo')
    op.drop_column('game', 'home')
    ### end Alembic commands ###
