"""change from int to strings

Revision ID: bd38d7b8d26e
Revises: edf24a715f92
Create Date: 2016-07-20 12:16:23.318367

"""

# revision identifiers, used by Alembic.
revision = 'bd38d7b8d26e'
down_revision = 'edf24a715f92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
