"""change from int to strings

Revision ID: d580fb834fa3
Revises: bd38d7b8d26e
Create Date: 2016-07-20 12:19:22.522612

"""

# revision identifiers, used by Alembic.
revision = 'd580fb834fa3'
down_revision = 'bd38d7b8d26e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
