"""init

Revision ID: edf24a715f92
Revises: 
Create Date: 2016-07-20 12:01:05.027581

"""

# revision identifiers, used by Alembic.
revision = 'edf24a715f92'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
