"""remove vars

Revision ID: f44bbd91e24d
Revises: d580fb834fa3
Create Date: 2016-07-20 12:24:39.877022

"""

# revision identifiers, used by Alembic.
revision = 'f44bbd91e24d'
down_revision = 'd580fb834fa3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'pens_runs')
    op.drop_column('game', 'home')
    op.drop_column('game', 'oppo_runs')
    op.drop_column('game', 'oppo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('oppo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('oppo_runs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('home', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('pens_runs', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
